-- SQLite removal (2026-09-16): zey_batch now talks to Postgres directly for
-- every read/write instead of mirroring a local SQLite file. The app used to
-- rely on SQLite's AUTOINCREMENT to mint new ids and push the finished row
-- to Supabase; these tables were created as plain `bigint primary key` with
-- no default, so a direct INSERT that omits the id (the new app code does
-- this) would fail. Add IDENTITY so Postgres mints new ids itself, starting
-- above whatever the SQLite-era mirror already pushed in.
do $$
declare
  rec record;
  maxid bigint;
begin
  for rec in select * from (values
    ('customers', 'customer_id'), ('services', 'service_id'),
    ('employees', 'employee_id'), ('transactions', 'transaction_id'),
    ('sms_history', 'sms_id'), ('email_history', 'email_id'),
    ('campaigns', 'campaign_id'), ('sync_log', 'log_id')
  ) as x(t, col)
  loop
    execute format('select coalesce(max(%I), 0) from public.%I', rec.col, rec.t) into maxid;
    execute format(
      'alter table public.%I alter column %I add generated by default as identity (start with %s)',
      rec.t, rec.col, maxid + 1
    );
  end loop;
end $$;
